version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./path/to/frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: ./path/to/backend/Dockerfile
    ports:
      - "3001:3001"
