name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Build Docker Image
      run: docker build -t kentucky-bros:latest .  # Replace with your actual build process

    - name: Upload app to TdA
      uses: Tour-de-App/upload-app@tda-24  # This is the custom action provided by Tour-de-App
      with:
        # You'll need to pass parameters or secrets required by this action
        team_secret: ${{ secrets.d13a03333c4edf3220252d546d7be510 }}  # Example of using a GitHub secret
        # Add other required parameters for the custom action here

