name: 'Upload app to TdA'
description: 'Upload action for the NK of TdA24 competition – staging setting.'
author: 'Student Cyber Games'
inputs:
  image_name:
    description: 'The name of docker image'
    required: true
  image_path:
    description: 'The path of docker image'
    required: true
  team_secret:
    description: 'Team secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get Deploy Access
      id: deployAccess
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://auth.registry.tourdeapp.eu/staging-auth'
        method: 'POST'
        data: '{"team_secret": "${{ inputs.team_secret }}"}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: registry.tourdeapp.eu
        username: tourdeapp
        password: ${{ fromJson(steps.deployAccess.outputs.response).key }}
    - name: Load and push image
      env:
          IMAGE: ${{ fromJson(steps.deployAccess.outputs.response).name }}
      shell: bash
      run: |
        docker load --input ${{ inputs.image_path }}
        docker tag ${{ inputs.image_name }} $IMAGE
        docker push $IMAGE
